create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  role text not null default 'volunteer' check (role in ('owner', 'volunteer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.volunteers (email, role, active)
values ('pavsingx@gmail.com', 'owner', true)
on conflict (email) do update set role = excluded.role, active = true;

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  registration_id text not null unique,
  full_name text not null,
  mobile text not null,
  email text,
  date_of_birth date,
  address_line_1 text not null,
  address_line_2 text,
  city text not null,
  postcode text not null,
  emergency_name text not null,
  emergency_phone text not null,
  emergency_relationship text not null,
  medical_notes text,
  consent boolean not null default false,
  created_at timestamptz not null default now(),
  checked_in_at timestamptz,
  registered_by uuid references auth.users(id)
);

create index if not exists idx_participants_full_name on public.participants (full_name);
create index if not exists idx_participants_mobile on public.participants (mobile);
create index if not exists idx_participants_checked_in on public.participants (checked_in_at);

alter table public.volunteers enable row level security;
alter table public.participants enable row level security;

create policy "volunteers can read their own access"
on public.volunteers for select to authenticated
using (email = lower(auth.jwt() ->> 'email'));

create policy "active volunteers can read participants"
on public.participants for select to authenticated
using (
  exists (
    select 1 from public.volunteers
    where email = lower(auth.jwt() ->> 'email') and active = true
  )
);

create policy "active volunteers can register participants"
on public.participants for insert to authenticated
with check (
  registered_by = auth.uid()
  and exists (
    select 1 from public.volunteers
    where email = lower(auth.jwt() ->> 'email') and active = true
  )
);

create policy "active volunteers can check in participants"
on public.participants for update to authenticated
using (
  exists (
    select 1 from public.volunteers
    where email = lower(auth.jwt() ->> 'email') and active = true
  )
)
with check (
  exists (
    select 1 from public.volunteers
    where email = lower(auth.jwt() ->> 'email') and active = true
  )
);
